# Generated by Django 5.0.6 on 2024-07-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
