# Generated by Django 5.0.6 on 2024-07-05 03:59

import django.db.models.deletion
import django.utils.timezone
import interns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interns',
            fields=[
                ('intern_code', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('intern_photo', models.ImageField(blank=True, null=True, upload_to=interns.models.upload_to)),
                ('full_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('job_title', models.CharField(choices=[('Intern', 'Intern'), ('Trainee', 'Trainee')], default='Intern', max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('institute', models.CharField(max_length=100)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('zip', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateField(default=django.utils.timezone.now)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.nationalities')),
            ],
        ),
    ]
